name: Build and Publish
on:
  workflow_dispatch: {}
  push:
    branches:
    - master

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Get app version from metadata file
      id: set_var
      run: |
        content=`cat ./manifest.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=manifestJson::$content"
    - name: Get short commit hash
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: |
          BUILD_VERSION=${{ github.run_number }}
          COMMIT_HASH=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          ghcr.io/${{ github.repository }}:${{ fromJson(steps.set_var.outputs.manifestJson).version }}
